<main>
    <section class="about__container">
        <h1>Qui sommes-nous ?</h1>
        <article>
            <img class="about__team__img" src="./vendor/images/office-4830639_1920.jpg" alt="Naïs CHATELLIER">
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Minus deserunt expedita aliquam ad eaque beatae quam tenetur magnam aliquid? Illum culpa natus cupiditate aut, iusto amet! Voluptates quisquam neque quam.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi consequuntur rem rerum, quaerat excepturi totam placeat libero molestiae, aliquam fugiat maxime consequatur officia quisquam nemo cumque illo aspernatur accusantium quo.</p>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quod repellendus ex voluptas temporibus eaque illum omnis eum consequatur animi tempora explicabo, facere corporis numquam commodi cum! Iste natus voluptatem deserunt.</p>
        </article>
        <h1>En quoi pouvons-nous vous aider ?</h1>
        <article>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Minus deserunt expedita aliquam ad eaque beatae quam tenetur magnam aliquid? Illum culpa natus cupiditate aut, iusto amet! Voluptates quisquam neque quam.</p>
        </article>
        <h1>Nos dernières créations</h1>
        <article>
            <img src="" alt="Robe de mariée">
        </article>
    </section>
</main>