<footer class="bg--primary">
    <img class="footer__logo" src="./vendor/images/LOGO-BLANC-TOTAL.png" alt="Brand Logo">
    <section>
        <a class="menu__link" href=""><i class="menu__icon fa-brands fa-facebook-f"></i></a>
        <a class="menu__link" href=""><i class="menu__icon fa-brands fa-instagram"></i></a>
        <a class="menu__link" href=""><i class="menu__icon fa-brands fa-tiktok"></i></a>
        <a class="menu__link" href=""><i class="menu__icon fa-brands fa-twitter"></i></a>
    </section>
    <section class="footer__infos">
        <div class="footer__nav">
            <a class="menu__link" href="index.php?page=Accueil">Accueil</a>
            <a class="menu__link" href="index.php?page=Produits">Nos produits</a>
            <a class="menu__link" href="index.php?page=Services">Nos services</a>
            <a class="menu__link" href="index.php?page=APropos">Qui sommes nous ?</a>
            <a class="menu__link" href="index.php?page=Contact">Nous contacter</a>
        </div>
        <div>
            <p>Nous retrouver</p>
            <address>
                3 impasse des Pervenches<br />
                44220 COUERON
            </address>
            <span>
                07.78.54.14.26
            </span>
        </div>
    </section>
</footer>
</body>

</html>