<main>
    <section class="services__option">
        <h1>Achat-Vente</h1>
        <article>
            <h3>Textiles, accessoires, chaussures</h3>
            <img src="" alt="Achat-Vente">
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis culpa distinctio debitis explicabo. Aliquam laborum aut dolore tempore magni deleniti. Hic inventore quae laudantium cupiditate dolorem modi assumenda molestiae optio.</p>
        </article>
    </section>
    <section class="services__option">
        <h1>Couture</h1>
        <article>
            <p>Ourlets</p>
            <p>Modification de pièces</p>
            <p>Reprise de tailles</p>
        </article>
    </section>
    <section class="services__option">
        <h1>Frip' à domicile</h1>
        <article class="">
            <p>Camion ambulant <em>(Coming soon...)</em></p>
            <p>Vente et rachat chez le particulier</p>
            <div class="calendar calendly-inline-widget" data-url="https://calendly.com/dfripetvous"></div>
            <script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js" async></script>
        </article>
    </section>
    <section class="services__option">
        <h1>Carte de Frip'élité</h1>
        <article>
            <p>Remises sur le service couture</p>
            <p>Remises sur la vente de vêtements à chaque date anniversaire (date de naissance et date d'inscription)</p>
        </article>
    </section>
</main>